spring.application.name=biblioteca-backend

# Supabase PostgreSQL Cloud
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.zhgljizufnopnjjgfzjb
spring.datasource.password=.Biblio*#0328
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
